class LocalizationEs {
    static final Map<String, String> texts = {
        "MN_MANAGE": "Gestionar",
        "MN_PLAY": "Jugar",
        "MN_SETTINGS": "Configuración",
        "ST_LANGUAGE": "Idioma",
        "ST_THEME": "Tema",
        "ST_GAME_COLORS": "Colores del juego",
        "ST_GAME_COLOR_CORRECT": "Color de acierto",
        "ST_GAME_COLOR_WRONG": "Color de fallo",
        "ST_GAME_COLOR_NEUTRAL": "Color de neutral",
        "CONFIRM_POPUP_TITLE": "¿Seguro?",
        "DELETE_GAME_CONFIRM": "¿Seguro que quieres borrar este juego?",
        "CANCEL": "Cancelar",
        "ERROR": "Error",
        "ACCEPT": "Aceptar",
        "DELETE": "Borrar",
        "RESTART": "Reiniciar",
        "NO_VALUE": "Sin valor",
        "IMPORTED_GAME_ERROR": "Error al importar el juego",
        "INFO_KEYS_NAME_HEADER": "Nombre",
        "INFO_KEYS_TYPE_HEADER": "Tipo",
        "INFO_KEYS_DESC_HEADER": "Descripción",
        "GAME_INFO": "Información",
        "ERROR_NO_GAME_INFO": "No hay información de este juego",
        "INFO_AUTHOR": "Autor",
        "INFO_VERSION": "Versión",
        "INFO_GAME_TYPE": "Tipo",
        "INFO_DESCRIPTION": "Descripción",
        "INFO_KEYS_HEADER": "Claves de este juego",
        "NO_GAMES_INSTALLED": "No tienes juegos instalados ¡pulsa arriba para gestionar y añadir juegos!",
        "IMPORTED_GAME": "Juego importado",
        "RESTART_PLAY_CONFIRM": "¿Seguro que quieres reiniciar?",
        "PLAY_WIN": "¡Ganaste!",
        "KEYBOARD_PLACEHOLDER": "Escribe abajo y selecciona arriba",
    };
}