class LocalizationEn {
    static final Map<String, String> texts = {
        "MN_MANAGE": "Manage",
        "MN_PLAY": "Play",
        "MN_SETTINGS": "Settings",
        "ST_LANGUAGE": "Language",
        "ST_THEME": "Theme",
        "CONFIRM_POPUP_TITLE": "Confirm?",
        "DELETE_GAME_CONFIRM": "Are you sure you want to delete this game?",
        "CANCEL": "Cancel",
        "ERROR": "Error",
        "ACCEPT": "Accept",
        "DELETE": "Delete",
        "RESTART": "Restart",
        "NO_VALUE": "No value",
        "IMPORTED_GAME_ERROR": "Error when importing a game",
        "INFO_KEYS_NAME_HEADER": "Key Name",
        "INFO_KEYS_TYPE_HEADER": "Key Type",
        "INFO_KEYS_DESC_HEADER": "Key Description",
        "GAME_INFO": "Game Info",
        "ERROR_NO_GAME_INFO": "No Game Info",
        "INFO_AUTHOR": "Author",
        "INFO_VERSION": "Version",
        "INFO_GAME_TYPE": "Type",
        "INFO_DESCRIPTION": "Description",
        "INFO_KEYS_HEADER": "Keys of this game",
        "NO_GAMES_INSTALLED": "You have no games installed, press the top button to manage and add your games!",
        "IMPORTED_GAME": "Imported Game",
        "RESTART_PLAY_CONFIRM": "Are you sure you want to restart?",
        "PLAY_WIN": "You Win!",
        "KEYBOARD_PLACEHOLDER": "Type down and select up here",
    };
}